Repository pytorch/text, pull requests merged in 2022-10, with the labels that each got.

#1923 Set release version, base PyTorch version and upload channel
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1918 [Feature] Add ability to load HF checkpoints into T5 model
  .github/workflows/integration-test.yml
  test/integration_tests/prototype/test_models.py
  torchtext/prototype/models/t5/bundler.py
Labels: cla signed

#1927 Updating usage of `torch.utils.data.graph.traverse` in test case
  test/torchtext_unittest/datasets/common.py
Labels: cla signed

#1932 [CI] Fix upload channel
  packaging/pkg_helpers.bash
Labels: cla signed

#1930 Avoid using std::regex and fix lint errors
  torchtext/csrc/gpt2_bpe_tokenizer.cpp
  torchtext/csrc/gpt2_bpe_tokenizer.h
  torchtext/csrc/register_pybindings.cpp
Labels: cla signed

#1937 [CI] Fix upload channel (#1932)
  packaging/pkg_helpers.bash
Labels: cla signed

#1934 update dataset RTE information
  torchtext/datasets/rte.py
Labels: cla signed

#1939 Revert "[CI] Fix upload channel (#1932)"
  packaging/pkg_helpers.bash
Labels: cla signed

#1940 [CI] Change upload channel for release
  packaging/pkg_helpers.bash
Labels: cla signed

#1942 Fixed on_disk_cache issues
  test/torchtext_unittest/datasets/test_cnndm.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2017.py
Labels: cla signed

#1945 Fixed on_disk_cache issues (#1942)
  test/torchtext_unittest/datasets/test_cnndm.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2017.py
Labels: cla signed

#1925 Update decoding logic to handle special tokens
  test/torchtext_unittest/test_transforms.py
  torchtext/csrc/gpt2_bpe_tokenizer.cpp
  torchtext/csrc/gpt2_bpe_tokenizer.h
Labels: cla signed

#1944 Fix device mismatch bug in T5 implementation
  torchtext/prototype/models/t5/modules.py
Labels: bug, cla signed

#1946 Add Character Level BPE Tokenizer (#1936)
  docs/requirements.txt
  docs/source/transforms.rst
  packaging/torchtext/meta.yaml
  test/torchtext_unittest/asset/openai-gpt-merges.txt
  test/torchtext_unittest/asset/openai-gpt-vocab.json
  test/torchtext_unittest/test_transforms.py
  torchtext/transforms.py
Labels: cla signed

#1953 Use re instead of regex
  packaging/torchtext/meta.yaml
  torchtext/transforms.py
Labels: cla signed

#1954 [Nova] Adding Smoke Tests for Binary Release
  test/smoke_tests/smoke_tests.py
Labels: cla signed

#1957 Fixed on_disk_cache issues (#1942) (#1945)
  test/torchtext_unittest/datasets/test_cnndm.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2017.py
Labels: cla signed

#1959 [Nova] Add caller workflow for Linux Conda Builds
  .github/workflows/build-linux-conda.yml
Labels: cla signed

#1961 Add Torchdata as a requirement and remove conditional imports of Torchdata
  packaging/torchtext/meta.yaml
  setup.py
  torchtext/_download_hooks.py
  torchtext/datasets/ag_news.py
  torchtext/datasets/amazonreviewfull.py
  torchtext/datasets/amazonreviewpolarity.py
  torchtext/datasets/cc100.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/cola.py
  torchtext/datasets/conll2000chunking.py
  torchtext/datasets/dbpedia.py
  torchtext/datasets/enwik9.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2016.py
  torchtext/datasets/iwslt2017.py
  torchtext/datasets/mnli.py
  torchtext/datasets/mrpc.py
  torchtext/datasets/multi30k.py
  torchtext/datasets/penntreebank.py
  torchtext/datasets/qnli.py
  torchtext/datasets/qqp.py
  torchtext/datasets/rte.py
  torchtext/datasets/sogounews.py
  torchtext/datasets/squad1.py
  torchtext/datasets/squad2.py
  torchtext/datasets/sst2.py
  torchtext/datasets/stsb.py
  torchtext/datasets/udpos.py
  torchtext/datasets/wikitext103.py
  torchtext/datasets/wikitext2.py
  torchtext/datasets/wnli.py
  torchtext/datasets/yahooanswers.py
  torchtext/datasets/yelpreviewfull.py
  torchtext/datasets/yelpreviewpolarity.py
Labels: cla signed

#1955 [Nova] Linux CPU GHA for Unittests
  .github/workflows/test-linux-cpu.yml
Labels: cla signed

#1962 Add Torchdata as a requirement and remove conditional imports of Torchdata (#1961)
  packaging/torchtext/meta.yaml
  setup.py
  torchtext/_download_hooks.py
  torchtext/datasets/ag_news.py
  torchtext/datasets/amazonreviewfull.py
  torchtext/datasets/amazonreviewpolarity.py
  torchtext/datasets/cc100.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/cola.py
  torchtext/datasets/conll2000chunking.py
  torchtext/datasets/dbpedia.py
  torchtext/datasets/enwik9.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2016.py
  torchtext/datasets/iwslt2017.py
  torchtext/datasets/mnli.py
  torchtext/datasets/mrpc.py
  torchtext/datasets/multi30k.py
  torchtext/datasets/penntreebank.py
  torchtext/datasets/qnli.py
  torchtext/datasets/qqp.py
  torchtext/datasets/rte.py
  torchtext/datasets/sogounews.py
  torchtext/datasets/squad1.py
  torchtext/datasets/squad2.py
  torchtext/datasets/sst2.py
  torchtext/datasets/stsb.py
  torchtext/datasets/udpos.py
  torchtext/datasets/wikitext103.py
  torchtext/datasets/wikitext2.py
  torchtext/datasets/wnli.py
  torchtext/datasets/yahooanswers.py
  torchtext/datasets/yelpreviewfull.py
  torchtext/datasets/yelpreviewpolarity.py
Labels: cla signed

#1963 [Nova] Rename Linux Conda Caller Workflow
  .github/workflows/build-conda-linux.yml
Labels: cla signed

#1968 Revert "Add Torchdata as a requirement and remove conditional imports of Torchdata"
  packaging/torchtext/meta.yaml
  setup.py
  torchtext/_download_hooks.py
  torchtext/datasets/ag_news.py
  torchtext/datasets/amazonreviewfull.py
  torchtext/datasets/amazonreviewpolarity.py
  torchtext/datasets/cc100.py
  torchtext/datasets/cnndm.py
  torchtext/datasets/cola.py
  torchtext/datasets/conll2000chunking.py
  torchtext/datasets/dbpedia.py
  torchtext/datasets/enwik9.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2016.py
  torchtext/datasets/iwslt2017.py
  torchtext/datasets/mnli.py
  torchtext/datasets/mrpc.py
  torchtext/datasets/multi30k.py
  torchtext/datasets/penntreebank.py
  torchtext/datasets/qnli.py
  torchtext/datasets/qqp.py
  torchtext/datasets/rte.py
  torchtext/datasets/sogounews.py
  torchtext/datasets/squad1.py
  torchtext/datasets/squad2.py
  torchtext/datasets/sst2.py
  torchtext/datasets/stsb.py
  torchtext/datasets/udpos.py
  torchtext/datasets/wikitext103.py
  torchtext/datasets/wikitext2.py
  torchtext/datasets/wnli.py
  torchtext/datasets/yahooanswers.py
  torchtext/datasets/yelpreviewfull.py
  torchtext/datasets/yelpreviewpolarity.py
Labels: cla signed

#1967 [Nova] Updated Smoke Tests that Account for Recursive Import
  test/smoke_tests/smoke_tests.py
Labels: cla signed

#1971 [Nova] Binary Build Workflows should use PR and not nightly on PRs
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-wheels-linux.yml
Labels: cla signed

#1964 [Nova] Caller workflow for Mac x86 Wheels
  .github/workflows/build-wheels-macos.yml
Labels: cla signed

#1969 [Nova] Mac x86 Unittests
  .github/workflows/test-macos-cpu.yml
Labels: cla signed

#1977 Ensure decoder mask is on same device as other tensors
  torchtext/prototype/models/t5/model.py
Labels: cla signed

#1973 [Nova] Add Caller for Mac x86 Conda Binaries
  .github/workflows/build-conda-macos.yml
Labels: enhancement, cla signed, testing

#1974 [Nova] Pass the smoke test scripts to Reusable Workflow
  .github/workflows/build-conda-linux.yml
  .github/workflows/build-wheels-linux.yml
  .github/workflows/build-wheels-macos.yml
Labels: enhancement, cla signed, testing
