Repository pytorch/text, pull requests merged in 2022-06, with the labels that each got.

#1717 Add support for QNLI dataset with unit tests
  docs/source/datasets.rst
  test/datasets/test_qnli.py
  torchtext/datasets/__init__.py
  torchtext/datasets/qnli.py
Labels: cla signed

#1724 Add support for WNLI dataset with unit tests
  docs/source/datasets.rst
  test/datasets/test_wnli.py
  torchtext/datasets/__init__.py
  torchtext/datasets/wnli.py
Labels: cla signed

#1745 Adding support for batch input in BERT Tokenizer with perf benchmark
  benchmark/benchmark_bert_tokenizer.py
  torchtext/csrc/bert_tokenizer.cpp
  torchtext/csrc/bert_tokenizer.h
  torchtext/csrc/register_pybindings.cpp
  torchtext/csrc/register_torchbindings.cpp
  torchtext/transforms.py
Labels: cla signed

#1742 Add contributing guidelines for third party and custom C++ operators
  CONTRIBUTING.md
Labels: cla signed

#1755 Add recommendations regarding use of datapipes for multi-processing, shuffling, DDP, etc.
  docs/source/datasets.rst
  examples/tutorials/sst2_classification_non_distributed.py
  torchtext/datasets/ag_news.py
  torchtext/datasets/amazonreviewfull.py
  torchtext/datasets/amazonreviewpolarity.py
  torchtext/datasets/cc100.py
  torchtext/datasets/cola.py
  torchtext/datasets/conll2000chunking.py
  torchtext/datasets/dbpedia.py
  torchtext/datasets/enwik9.py
  torchtext/datasets/imdb.py
  torchtext/datasets/iwslt2016.py
  torchtext/datasets/iwslt2017.py
  torchtext/datasets/mnli.py
  torchtext/datasets/mrpc.py
  torchtext/datasets/multi30k.py
  torchtext/datasets/penntreebank.py
  torchtext/datasets/qqp.py
  torchtext/datasets/sogounews.py
  torchtext/datasets/squad1.py
  torchtext/datasets/squad2.py
  torchtext/datasets/sst2.py
  torchtext/datasets/stsb.py
  torchtext/datasets/udpos.py
  torchtext/datasets/wikitext103.py
  torchtext/datasets/wikitext2.py
  torchtext/datasets/yahooanswers.py
  torchtext/datasets/yelpreviewfull.py
  torchtext/datasets/yelpreviewpolarity.py
Labels: cla signed

#1759 Fix bug in RTE and WNLI testing
  test/datasets/test_rte.py
  test/datasets/test_wnli.py
  torchtext/datasets/rte.py
Labels: cla signed

#1760 Fix bug in QNLI dataset and corresponding test
  test/datasets/test_qnli.py
  torchtext/datasets/qnli.py
Labels: cla signed

#1761 Fix windows utils test
  test/test_utils.py
Labels: cla signed

#1762 Set release version and base pytorch version
  .circleci/config.yml
  .circleci/config.yml.in
Labels: cla signed

#1765 Removing experimental folders from torchtext
  packaging/torchtext/meta.yaml
  test/experimental/__init__.py
  test/experimental/test_functional.py
  test/experimental/test_transforms.py
  test/experimental/test_vectors.py
  test/experimental/test_with_asset.py
  torchtext/__init__.py
  torchtext/experimental/__init__.py
  torchtext/experimental/asset/get_checksum.sh
  torchtext/experimental/asset/get_checksums_fast_text.py
  torchtext/experimental/transforms.py
  torchtext/experimental/vectors.py
  torchtext/experimental/vocab_factory.py
Labels: cla signed

#1758 fix missed mask arg in torchtext transformer
  torchtext/models/roberta/modules.py
Labels: cla signed

#1768 [cherry-pick] Fix missed mask arg in torchtext transformer (#1758)
  torchtext/models/roberta/modules.py
Labels: cla signed

#1769 Update nightly version to 0.14
  version.txt
Labels: cla signed

#1763 Migrate RegexTokenizer from experimental/transforms.py to transforms.py
  test/experimental/test_functional.py
  test/test_transforms.py
  torchtext/experimental/transforms.py
  torchtext/transforms.py
Labels: cla signed

#1770 Add test to compare encoder inference on input with and without padding
  test/models/test_transformers.py
Labels: cla signed, testing

#1773 Refactor TorchText version handing and adding first version of M1 builds
  .github/workflows/build-m1-binaries.yml
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
Labels: cla signed

#1767 Updated doctree for 0.13.0 release candidate
  versions.html
Labels: cla signed

#1776 Add m1 tagged build for torchtext
  .github/workflows/build-m1-binaries.yml
  packaging/pkg_helpers.bash
Labels: cla signed

#1782 Add missing type hints
  test/data/test_functional.py
  torchtext/data/functional.py
  torchtext/data/utils.py
  torchtext/experimental/transforms.py
  torchtext/experimental/vectors.py
  torchtext/models/roberta/model.py
  torchtext/models/roberta/modules.py
  torchtext/nn/modules/multiheadattention.py
  torchtext/transforms.py
  torchtext/vocab/vectors.py
  torchtext/vocab/vocab.py
Labels: cla signed

#1784 Refactor TorchText version handing and adding first version of M1 bui…
  .github/workflows/build-m1-binaries.yml
  packaging/build_conda.sh
  packaging/build_wheel.sh
  packaging/pkg_helpers.bash
Labels: cla signed

#1785 Add m1 tagged build for torchtext (#1776)
  .github/workflows/build-m1-binaries.yml
  packaging/pkg_helpers.bash
Labels: cla signed

#1786 Fix typo in nightly branch ref (#1783)
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#1787 sharing -> sharding
  docs/source/datasets.rst
Labels: cla signed

#1775 Migrate MaskTransform from internal to experimental/transforms.py
  test/experimental/test_transforms.py
  torchtext/experimental/transforms.py
Labels: cla signed

#1790 Making sure we build correctly against release branch
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#1791 Making sure we build correctly against release branch (#1790)
  .github/workflows/build-m1-binaries.yml
Labels: cla signed

#1794 Adding the conda builds for m1
  .github/workflows/build-m1-binaries.yml
  packaging/pkg_helpers.bash
Labels: cla signed

#1795 Adding the conda builds for m1 (#1794)
  .github/workflows/build-m1-binaries.yml
  packaging/pkg_helpers.bash
Labels: cla signed

#1684 Add benchmark for roberta prepoc pipelines
  benchmark/benchmark_roberta_pipeline.py
  examples/data_pipeline/roberta_dataframe.py
  examples/data_pipeline/roberta_datapipe.py
Labels: cla signed

#1799 remove padding mask for input embeddings
  torchtext/models/roberta/modules.py
Labels: cla signed

#1789 Add CNN-DM dataset to torchtext
  test/datasets/test_cnndm.py
  torchtext/data/datasets_utils.py
  torchtext/datasets/cnndm.py
Labels: cla signed

#1801 Adding Benchmark for TA ops
  benchmark/benchmark_torcharrow_ops.py
Labels: cla signed

#1805 Automatically initialize submodule
  .circleci/unittest/linux/scripts/install.sh
  .circleci/unittest/windows/scripts/install.sh
  packaging/torchtext/bld.bat
  packaging/torchtext/build.sh
  setup.py
Labels: cla signed, BE hackathon

#1804 Rename build_tools dir to tools dir
  setup.py
  tools/__init__.py
  tools/conda/torchtext/meta.yaml
  tools/setup_helpers/__init__.py
  tools/setup_helpers/extension.py
Labels: cla signed, BE hackathon

#1803 converting experimental to prototype
  benchmark/benchmark_basic_english_normalize.py
  benchmark/benchmark_experimental_vectors.py
  benchmark/benchmark_pytext_vocab.py
  benchmark/benchmark_sentencepiece.py
  benchmark/benchmark_vocab.py
  benchmark/data_construction.py
  examples/text_classification/predict.py
  examples/text_classification/train.py
  packaging/torchtext/meta.yaml
  test/prototype/__init__.py
  test/prototype/test_functional.py
  test/prototype/test_transforms.py
  test/prototype/test_vectors.py
  test/prototype/test_with_asset.py
  torchtext/__init__.py
  torchtext/experimental/__init__.py
  torchtext/experimental/transforms.py
  torchtext/experimental/vectors.py
  torchtext/experimental/vocab_factory.py
  torchtext/prototype/__init__.py
  torchtext/prototype/asset/get_checksum.sh
  torchtext/prototype/asset/get_checksums_fast_text.py
  torchtext/prototype/transforms.py
  torchtext/prototype/vectors.py
  torchtext/prototype/vocab_factory.py
Labels: cla signed, BE hackathon

#1798 Add Datasets contribution guidelines
  CONTRIBUTING_DATASETS.md
  docs/source/datasets.rst
Labels: cla signed

#1807 Adding benchmarks for add_tokens operator
  benchmark/benchmark_torcharrow_ops.py
Labels: cla signed

#1810 [BUG FIX] Fixing incorrect inputs to add_eos and_bos operators in torcharrow operator benchmark
  benchmark/benchmark_torcharrow_ops.py
Labels: cla signed

#1802 [MERGE AT RELEASE] Update compatibility matrix for 0.13 release
  README.rst
Labels: cla signed
