Repository pytorch/text, pull requests merged in 2023-03, with the labels that each got.

#2091 Fix UTF8 decoding error in GPT2BPETokenizer `decode` method
  torchtext/csrc/register_pybindings.cpp
Labels: cla signed

#2092 [cherry-pick] Fix UTF8 decoding error in GPT2BPETokenizer `decode` method
  torchtext/csrc/register_pybindings.cpp
Labels: cla signed

#2097 Update tutorial to match PyTorch main tutorials page
  examples/tutorials/t5_demo.py
Labels: cla signed

#2096 Include padding mask in generation
  test/integration_tests/test_generate.py
  torchtext/models/t5/model.py
  torchtext/prototype/generate.py
Labels: cla signed

#2104 Add decorator to skip tests and log a warning if URL is unaccessible
  test/torchtext_unittest/common/torchtext_test_case.py
  test/torchtext_unittest/test_build.py
Labels: cla signed

#2105 Update author and author email
  setup.py
Labels: cla signed, BE hackathon

#2109 Updated doctree for 0.15.0 release candidate
  versions.html
Labels: cla signed

#2117 Bump version
  version.txt
Labels: cla signed

#2116 Updated doctree for 0.15.0 stable release
  versions.html
Labels: cla signed

#2115 Set stable symlink to 0.15.1
  stable
Labels: cla signed

#2120 Set stable to 0.15.0
  stable
Labels: cla signed

#2119 Fix title underline
  examples/tutorials/t5_demo.py
Labels: docs, cla signed

#2124 Update version.txt to 0.15.1
  version.txt
Labels: cla signed

#2129 Simplify torchdata version extraction in packaging script
  packaging/install_torchdata.sh
Labels: cla signed

#2131 Add shift-right method to T5 model
  test/torchtext_unittest/models/t5_models_test_impl.py
  torchtext/models/t5/model.py
Labels: cla signed

#2118 Small fixes in Readme
  README.rst
  torchtext/transforms.py
Labels: cla signed

#2134 Optionally ignore utf-8 decoding error for scripted C++ tokenizers. (…
  test/torchtext_unittest/test_transforms.py
  torchtext/csrc/register_pybindings.cpp
  torchtext/csrc/register_torchbindings.cpp
  torchtext/transforms.py
Labels: cla signed
